exports.EVOLUTION_EVENT = 'EVOLUTION_EVENT';
exports.CELLS_UPDATED_EVENT = 'CELLS_UPDATED_EVENT';
exports.NEW_CLIENT_EVENT = 'NEW_CLIENT_EVENT';
exports.UPDATE_CELLS_EVENT = 'UPDATE_CELLS_EVENT';
exports.SERVER_RESTARTED_EVENT = 'SERVER_RESTARTED_EVENT';
exports.WORLD_STARTED_EVENT = 'WORLD_STARTED_EVENT';