exports.EVOLUTION_EVENT = 'EVOLUTION_EVENT';
exports.CELLS_UPDATED_EVENT = 'CELLS_UPDATED_EVENT';
exports.NEW_CLIENT = 'NEW_CLIENT';
exports.UPDATE_CELLS = 'UPDATE_CELLS';
exports.SETUP = 'SETUP';
exports.SERVER_RESTARTED = 'SERVER_RESTARTED';